[/Script/Engine.Engine]
bUseFixedFrameRate=False

[/Script/Engine.RendererSettings]
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Shadow.Virtual.Enable=1
r.AntiAliasingMethod=4
r.TemporalAA.Upsampling=1
r.DefaultFeature.MotionBlur=True
r.DefaultFeature.AutoExposure=True
r.Lumen.Reflections.Allow=1
r.Nanite.ProjectEnabled=True

[/Script/EngineSettings.GameMapsSettings]
GameInstanceClass=/Script/Engine.GameInstance
EditorStartupMap=/Game/Maps/L_ApexCircuit
GameDefaultMap=/Game/Maps/L_ApexCircuit
GlobalDefaultGameMode=/Script/ApexCircuit.ApexCircuitGameMode

[/Script/Engine.PhysicsSettings]
bSubstepping=True
MaxSubstepDeltaTime=0.008333333
MaxSubsteps=8

[/Script/UnrealEd.ProjectPackagingSettings]
+DirectoriesToAlwaysStageAsNonUFS=(Path="Data")

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=410BB1AD5442AB04FD3896B17E9D2F70
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=
# Generated Android File Server defaults retained by Unreal.
